"""
Django settings for MtzCaps project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-!mc*$o8_uuu=yfjj!tul-yl+m1+t)+ut98ryf1_5ef##e7sjga')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not os.getenv('VERCEL', False)

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.200.200.248',  # Your local IP address
    '0.0.0.0',
    '.vercel.app',  # Allow all Vercel domains
    '*',  # Allow all hosts (only for development)
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'cloudinary_storage',
    'cloudinary',

    'shop'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MtzCaps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MtzCaps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Default to SQLite for local development
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Use PostgreSQL for production (Vercel)
if os.getenv('DATABASE_URL'):
    DATABASES['default'] = dj_database_url.parse(os.getenv('DATABASE_URL'))


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Static files finders - ensure all static files are discovered
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Static files configuration
if os.getenv('VERCEL'):
    # Production static files configuration for Vercel
    STATIC_ROOT = '/tmp/staticfiles'
    # Include shop static files even in Vercel environment
    STATICFILES_DIRS = []
    # Add shop static directory if it exists
    shop_static_dir = os.path.join(BASE_DIR, 'shop', 'static')
    if os.path.exists(shop_static_dir):
        STATICFILES_DIRS.append(shop_static_dir)
    # Disable static files storage since Vercel has limitations
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    # Local development static files configuration
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
    static_dir = os.path.join(BASE_DIR, 'static')
    if os.path.exists(static_dir):
        STATICFILES_DIRS = [static_dir]
    else:
        STATICFILES_DIRS = []

# Cloudinary configuration
try:
    import cloudinary
    import cloudinary.uploader
    import cloudinary.api
    
    # Configure Cloudinary using CLOUDINARY_URL environment variable
    if os.getenv('CLOUDINARY_URL'):
        cloudinary.config()
    else:
        # Fallback for local development
        cloudinary.config(
            cloud_name='your-local-cloud-name',
            api_key='your-local-api-key',
            api_secret='your-local-api-secret'
        )
    CLOUDINARY_AVAILABLE = True
except ImportError:
    # Cloudinary not installed, will use local storage
    CLOUDINARY_AVAILABLE = False
    print("Cloudinary not available, using local storage")

# Media files (User uploads)
if os.getenv('VERCEL') and CLOUDINARY_AVAILABLE:
    # Production: Use Cloudinary for media storage
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    MEDIA_URL = '/media/'  # This will be handled by Cloudinary
else:
    # Local development or fallback: Use local storage
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Site URL for absolute URLs in social media tags
if os.getenv('VERCEL'):
    # In production, this should be your actual domain
    SITE_URL = 'https://your-vercel-app.vercel.app'  # Replace with your actual Vercel domain
else:
    # Local development
    SITE_URL = 'http://localhost:8000'

# Stripe Settings
# WARNING: For production, move these to environment variables or a secure config system
STRIPE_PUBLISHABLE_KEY = 'pk_live_51RkBRZAyXnlVGbyz9dLB8dEzZiY8zqCFuIWshWp2ABuAKXOBwSN2d6ZOMW7GHU7xMviOCIfHygpIivQPJBBFtPc000DTDrfFkm'
STRIPE_SECRET_KEY = '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'
