# Generated by Django 4.2.23 on 2025-07-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hat_name', models.CharField(help_text='The name of the hat', max_length=200)),
                ('hat_category', models.CharField(help_text='Hat category', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in US dollars', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Optional description of the hat', null=True)),
                ('sold_out', models.BooleanField(default=False, help_text='Whether the hat is sold out')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hat',
                'verbose_name_plural': 'Hats',
                'ordering': ['hat_category', 'hat_name'],
            },
        ),
    ]
