# Generated by Django 4.2.23 on 2025-07-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_hat_hat_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='description_pic1',
            field=models.ImageField(blank=True, help_text='Optional additional description image 1', null=True, upload_to='hat_images/'),
        ),
        migrations.AddField(
            model_name='hat',
            name='description_pic2',
            field=models.ImageField(blank=True, help_text='Optional additional description image 2', null=True, upload_to='hat_images/'),
        ),
        migrations.AddField(
            model_name='hat',
            name='description_pic3',
            field=models.ImageField(blank=True, help_text='Optional additional description image 3', null=True, upload_to='hat_images/'),
        ),
    ]
