# Generated by Django 4.2.23 on 2025-07-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_hat_description_pic1_hat_description_pic2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('first_name', models.CharField(help_text="Customer's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Customer's last name", max_length=100)),
                ('address', models.CharField(help_text='Street address', max_length=200)),
                ('city', models.CharField(help_text='City', max_length=100)),
                ('state', models.CharField(help_text='State/Province', max_length=100)),
                ('zip_code', models.CharField(help_text='ZIP/Postal code', max_length=20)),
                ('country', models.CharField(default='US', help_text='Country', max_length=100)),
                ('stripe_payment_intent_id', models.CharField(help_text='Stripe PaymentIntent ID', max_length=200, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount paid', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('payment_status', models.CharField(default='pending', help_text='Payment status', max_length=50)),
                ('order_items', models.JSONField(help_text='JSON data of ordered items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
